name: dice_roll_app
description: "Dice Roll App with Flutter"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  google_nav_bar: ^5.0.6
  riverpod_annotation: ^2.3.5
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.2
  build_runner: ^2.4.12
  custom_lint: ^0.6.5
  riverpod_lint: ^2.3.12

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
